// patch_14_aip_series_button.js
// New TV-only "in progress" toggle button on the series detail page,
// mounted to the right of the "Actualizar metadatos" (sg) button.
// Hits the existing PUT/DELETE /api/actively-in-progress/:mediaItemId.
//
// Visual:
//   - active   (AIP excluded=0)            -> green outline + green text,
//                                            label "Quitar de en proceso"
//   - inactive (no AIP row OR excluded=1)  -> red outline + red text,
//                                            label "Marcar en proceso"
//
// Why: Reported 2026-05-26. Series like Euphoria/The Boys stay stuck in
// /in-progress after the user catches up on all aired episodes and there
// was no UI on the series page to remove them (per-episode AIP exists,
// but series-level did not). For non-TV the green "Lo estoy viendo/..."
// modal already covers this; we deliberately don't touch non-TV here.

;(() => {
const fs = require('fs');
const child = require('child_process');
const bundlePath = child.execSync('ls /app/public/main_*.js | grep -v "\\.LICENSE\\|\\.map"').toString().trim();
let c = fs.readFileSync(bundlePath, 'utf8');

const marker = '/*mt-fork:aip-series-button*/';
if (c.includes(marker)) {
  console.log('aip-series-button: already patched');
  return;
}

// === 1. _AIPS toggle component (TV series-level AIP toggle) ===
// Initial state comes from the detail payload (mi.activelyInProgress,
// populated by the item controller). After a click we drive the visual
// from local state and invalidate the HW (react-query) cache so other
// views (/in-progress, etc.) refresh.
const aipsDef = '_AIPS=function(e){' + marker +
  'var mi=e.mediaItem;' +
  'var _s=r.useState(!!mi.activelyInProgress),active=_s[0],setA=_s[1];' +
  'var toggle=function(){' +
    'var url="/api/actively-in-progress/"+mi.id;' +
    'var method=active?"DELETE":"PUT";' +
    'fetch(url,{method:method,credentials:"same-origin"}).then(function(r){return r.json()}).then(function(){' +
      'setA(!active);' +
      'try{HW.removeQueries(["items"])}catch(_){}; try{HW.invalidateQueries(["items"])}catch(_){}; try{HW.removeQueries(["details",mi.id])}catch(_){};' +
    '})' +
  '};' +
  'var color=active?"#16a34a":"#dc2626";' +
  'var style={' +
    'border:"1.5px solid "+color,' +
    'color:color,' +
    'borderRadius:"6px",' +
    'padding:"6px 12px",' +
    'cursor:"pointer",' +
    'textAlign:"center",' +
    'fontWeight:"500",' +
    'fontSize:"0.875rem",' +
    'background:"transparent",' +
    'userSelect:"none",' +
    'display:"flex",' +
    'alignItems:"center",' +
    'justifyContent:"center"' +
  '};' +
  'return r.createElement("div",{style:style,onClick:toggle,role:"button"},' +
    'active?"Quitar de en proceso":"Marcar en proceso"' +
  ')' +
'},';

const compAnchor = '_v=function(e){';
if ((c.split(compAnchor).length - 1) !== 1) {
  console.error('aip-series-button: _v anchor count != 1'); process.exit(1);
}
c = c.replace(compAnchor, aipsDef + compAnchor);
console.log('aip-series-button: injected _AIPS component');

// === 2. Mount _AIPS to the right of sg (Update metadata), TV only ===
// patch_09 moved the sg conditional to right after _AB. We anchor on the
// stable tail of that conditional (avoids the IGDB/TMDB/OL/Audible source
// list inside, which other patches mutate to add 'wikidata', etc.).
const sgTail = '(a)?r.createElement(sg,{mediaItem:a}):r.createElement("div")';
if ((c.split(sgTail).length - 1) !== 1) {
  console.error('aip-series-button: sg tail anchor count != 1 (patch_09 prerequisite?)'); process.exit(1);
}
const mountAddition = ',"tv"===a.mediaType?r.createElement(_AIPS,{mediaItem:a}):null';
c = c.replace(sgTail, sgTail + mountAddition);
console.log('aip-series-button: mounted _AIPS to the right of sg (TV-only)');

fs.writeFileSync(bundlePath, c);

// Syntax sanity check.
try {
  child.execSync('node --check ' + bundlePath, { stdio: 'pipe' });
  console.log('aip-series-button: bundle syntax OK');
} catch (e) {
  console.error('aip-series-button: SYNTAX ERROR -> ' + (String(e.message || '')).slice(0, 400));
  process.exit(1);
}

// .gz/.br siblings are regenerated by the Dockerfile post-patch step.
console.log('aip-series-button: complete');
})();
